### ISSUE TITLE
How to set custom drive label

### ISSUE THREAD

**Issue by ghost** [Daniel-Abrecht/fuse-nfs-crossbuild-scripts#2]
Hi
I've been testing this in my Windows 10 machine and I successfully  mounted multiple network shares, but the mountpoint label always reads "DOKAN" by default for the various 'drives' and this creates confusion.

Is it possible to set custom drive labels for mounts? (command line?)

I've tried rename them via windows explorer but after unmounting or rebooting system, they reset again to default.

**EDIT/UPDATE:** as workaround mounting to existing folders with an appropriate name and place them in `C:\Users\username\AppData\Roaming\Microsoft\Windows\Network Shortcuts` makes them appear on `This PC` file explorer (aka My Computer) as network location
(Windows 10)

**Comment by Daniel-Abrecht** [comment]
I'll have to make a change fuse-nfs for this. The option of dokan-fuse for this would be -ovolname=TheDriveLabel, but it currently can't be passed to dokan-fuses fuse_main using fuse-nfs. It currently parses all options itself using getopt, instead of letting libfuse handle that, which means that currently, fuse-nfs can't pass fuse options it doesn't know about to fuse. I could either change the argument parsing of fuse-nfs, but that would change the arguments it takes, or I could add that option specifically, but that won't work for other dokany specific fuse options. I'll make a pull request for the former in fuse-nfs first, but I'm not sure if it'll be accepted, it kind of breaks backward compatibility after all.

**Comment by Daniel-Abrecht** [comment]
Because it doesn't look like sahlberg/fuse-nfs#33 is going to be looked at, I've now added my repo to the fuse-nfs versions to be built. Just use one of the releases listed as `fuse-nfs=dpa`, and then you can use it like so:
```
fuse-nfs.exe -o volname="Volume Name" nfs://share-name-or-ip/your-export R:
```
